# Inserts a blank line between shell prompts
add_newline = true 

# Change command timeout from 500 to 1000ms
command_timeout = 1000

# Change the default prompt format
#format = """$env_var $all"""

format = """\
[┌──](240)$env_var \
$all[└](240)$character"""

# Change the default prompt characters
[character]
format = "$symbol "
success_symbol = "[\\$](yellow)"
error_symbol = "[\\$](red)"

# Shows an icon that should be included by FISH_CONFIG_DIR/conf.d/starship.fish
[env_var.DISTRO_ICON]
format = "[$env_value](bright-white)"
variable = "DISTRO_ICON"
disabled = false

# Disable some module
[battery]
disabled = true

# Shows the username
[username]
format = "[$user]($style)"
style_user = "white"
style_root = "white"
show_always = true
disabled = false

# Shows the system hostname
[hostname]
format = "[@](240)[$hostname](yellow)"
ssh_only = false
disabled = false

# Shows the path to your current directory
[directory]
format = '[─](240)[\[](240)[$path]($style)[$read_only]($read_only_style)[\]](240) '
home_symbol = " ~"
read_only = " "
truncation_symbol = "…/"
read_only_style = "red"
style = "bold blue"

