#
# ~/.bash_profile
#

# Start under Wayland
export XDG_SESSION_TYPE=wayland
export GDK_BACKEND=wayland
export BEMENU_BACKEND=wayland   
if [[ $XDG_SESSION_TYPE == "wayland" ]]; then
    export MOZ_ENABLE_WAYLAND=1
fi

# Starship
export STARSHIP_CONFIG="$HOME/.config/starship/starship.toml"
# Volta
export VOLTA_HOME="$HOME/.volta"
# Cargo
export CARGO_HOME="$HOME/.cargo"

# PATH
PATH="$HOME/.local/bin:$PATH"
PATH="$VOLTA_HOME/bin:$PATH"
PATH="$CARGO_HOME/bin:$PATH"

# Source ~/.bashrc
[[ -f ~/.bashrc ]] && . ~/.bashrc

# Autostart sway on TTY login 
# N: lines following a command using `exec` would be ignored.
if [[ -z $DISPLAY ]] && [[ "$(tty)" == "/dev/tty1" ]]; then
    exec sway
fi

