#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Use bash-completion, if available, with <TAB> <TAB>
[[ -r /usr/share/bash-completion/bash_completion ]] && \
  . /usr/share/bash-completion/bash_completion

# Check the window size after each command and, if necessary, update the values of LINES and COLUMNS
shopt -s checkwinsize

# Enable history appending instead of overwriting, so if you start a new terminal, you have old session history
shopt -s histappend
PROMPT_COMMAND='history -a'

# Expand the history size
export HISTFILESIZE=10000
export HISTSIZE=500

# Don't put duplicate lines in the history and don't add lines that start with a space
export HISTCONTROL=erasedups:ignoreboth

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

# Enable terminal title updates
case ${TERM} in
  xterm*|rxvt*|Eterm|alacritty*|aterm|kterm|gnome*)
    PROMPT_COMMAND=${PROMPT_COMMAND:+$PROMPT_COMMAND; }'printf "\033]0;%s@%s:%s\007" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/\~}"'

    ;;
  screen*)
    PROMPT_COMMAND=${PROMPT_COMMAND:+$PROMPT_COMMAND; }'printf "\033_%s@%s:%s\033\\" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/\~}"'
    ;;
esac

# Scripts
[[ -r $HOME/.dotfiles/bash/scripts.sh ]] && source $HOME/.dotfiles/bash/scripts.sh

# lf
#LFCD="$HOME/.dotfiles/lf/lfcd.sh"
#[[ -f $LFCD ]] && source $LFCD

# Setting fish as interective shell only
#if [[ $(ps --no-header --pid=$PPID --format=comm) != "fish" && -z ${BASH_EXECUTION_STRING} ]]
#then
#	exec fish
#fi

[[ -f ~/.fzf.bash ]] && source ~/.fzf.bash
eval "$(zoxide init bash)"
